// Auto-generated asset manifest
// This file is generated by scripts/build-test-app.js
// Do not edit manually!

export const ASSET_FILES = [
  {
    projectPath: '../../testAssets/short_en.raw',
    modulePath: require('../testAssets/short_en.raw')
  }
]
